//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElearningApplication.View.Instructor
{


    public partial class UploadMaterial
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// ddlCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCourses;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// fileUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
